In [2]:
import pandas as pd
import glob
import os
import numpy as np

In [4]:
files = sorted(glob.glob("C:/Users/CaseStudy1/*.csv"))

df_list = [pd.read_csv(file) for file in files]
df = pd.concat(df_list, ignore_index=True)
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5848698,F319CE4AE531709B,electric_bike,2026-05-02 15:34:11.090,2026-05-02 15:34:54.792,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,casual
5848699,C74AD329966F1E3D,electric_bike,2026-05-06 22:11:10.776,2026-05-06 22:11:13.621,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,member
5848700,944F31B24AEACDCB,electric_bike,2026-05-31 16:49:33.315,2026-05-31 17:01:39.539,Ada St & Washington Blvd,CHI00278,Damen Ave & Thomas St (Augusta Blvd),CHI00296,41.882830,-87.661206,41.901315,-87.677409,member
5848701,DCA6A24FC420D5AF,electric_bike,2026-05-20 18:35:36.360,2026-05-20 18:43:34.856,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member
5848702,4C020D893130AC87,electric_bike,2026-05-26 08:15:05.915,2026-05-26 08:22:55.788,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member

In [8]:
df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1249667
start_station_id      1249667
end_station_name      1314334
end_station_id        1314334
start_lat                   0
start_lng                   0
end_lat                  5896
end_lng                  5896
member_casual               0
dtype: int64

In [11]:
df.drop_duplicates()
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5848698,F319CE4AE531709B,electric_bike,2026-05-02 15:34:11.090,2026-05-02 15:34:54.792,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,casual
5848699,C74AD329966F1E3D,electric_bike,2026-05-06 22:11:10.776,2026-05-06 22:11:13.621,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,member
5848700,944F31B24AEACDCB,electric_bike,2026-05-31 16:49:33.315,2026-05-31 17:01:39.539,Ada St & Washington Blvd,CHI00278,Damen Ave & Thomas St (Augusta Blvd),CHI00296,41.882830,-87.661206,41.901315,-87.677409,member
5848701,DCA6A24FC420D5AF,electric_bike,2026-05-20 18:35:36.360,2026-05-20 18:43:34.856,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member
5848702,4C020D893130AC87,electric_bike,2026-05-26 08:15:05.915,2026-05-26 08:22:55.788,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member

In [12]:
df.drop_duplicates()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5848698,F319CE4AE531709B,electric_bike,2026-05-02 15:34:11.090,2026-05-02 15:34:54.792,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,casual
5848699,C74AD329966F1E3D,electric_bike,2026-05-06 22:11:10.776,2026-05-06 22:11:13.621,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,member
5848700,944F31B24AEACDCB,electric_bike,2026-05-31 16:49:33.315,2026-05-31 17:01:39.539,Ada St & Washington Blvd,CHI00278,Damen Ave & Thomas St (Augusta Blvd),CHI00296,41.882830,-87.661206,41.901315,-87.677409,member
5848701,DCA6A24FC420D5AF,electric_bike,2026-05-20 18:35:36.360,2026-05-20 18:43:34.856,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member
5848702,4C020D893130AC87,electric_bike,2026-05-26 08:15:05.915,2026-05-26 08:22:55.788,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member

In [23]:
df[df.duplicated()]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
5259122,C85BE84CF8D18F6D,classic_bike,2026-04-30 19:14:30.926,2026-05-01 15:16:20.829,Wentworth Ave & Cermak Rd*,CHI02021,Michigan Ave & 11th St,CHI02025,41.853214,-87.631872,41.869590,-87.623961,casual
5262656,D45C58C1A07DDA84,classic_bike,2026-04-30 23:58:46.712,2026-05-01 00:03:45.291,Clark St & Arlington Pl,CHI02109,Wilton Ave & Diversey Pkwy,CHI02052,41.926940,-87.641480,41.932418,-87.652705,member
5272949,2038F30519CBC7E5,electric_bike,2026-04-30 23:53:54.933,2026-05-01 00:03:35.194,Clark St & Berwyn Ave,CHI00530,Sheridan Rd & Loyola Ave,CHI00752,41.978017,-87.668019,42.001044,-87.661198,member
5274627,796A83D45529C7D8,electric_bike,2026-04-30 22:08:09.585,2026-05-01 00:46:55.672,Morgan St & Lake St,CHI00878,Wilton Ave & Belmont Ave,CHI00353,41.885492,-87.652289,41.940232,-87.652944,member
5287579,78D590AAA74CAE97,electric_bike,2026-04-30 23:47:13.998,2026-05-01 00:01:21.926,Sangamon St & Washington Blvd,CHI00439,Larrabee St & Webster Ave,CHI00454,41.883165,-87.651100,41.921822,-87.644140,member
5309739,5C56F4FB55D5B5F5,electric_bike,2026-04-30 23:52:06.627,2026-05-01 00:01:31.323,Ashland Ave & Grand Ave,CHI00362,Francisco Ave & Chicago Ave,CHI02080,41.891072,-87.666611,41.895745,-87.698653,casual
5346781,10117825A92C182D,classic_bike,2026-04-30 23:56:24.321,2026-05-01 00:01:51.860,Peoria St & Kinzie St,CHI02098,Ogden Ave & Chicago Ave,CHI00275,41.888960,-87.649730,41.896362,-87.654061,casual
5348606,D28B306F00821227,classic_bike,2026-04-30 23:57:36.236,2026-05-01 00:16:03.428,Clark St & Berwyn Ave,CHI00530,Clark St & Berwyn Ave,CHI00530,41.978017,-87.668019,41.978017,-87.668019,member
5376023,2034B29BDC8E2559,classic_bike,2026-04-30 19:40:30.929,2026-05-01 13:30:44.841,Broadway & Sheridan Rd,CHI00476,Clarendon Ave & Gordon Ter,CHI00455,41.952833,-87.649993,41.957867,-87.649505,member
5449497,3767A2E3310A5B0B,classic_bike,2026-04-30 00:24:47.685,2026-05-01 01:24:41.485,Halsted St & Lake St,CHI02121,NaN,NaN,41.885760,-87.647110,NaN,NaN,member
5454773,0612B2A21BA5E988,classic_bike,2026-04-30 15:56:11.305,2026-05-01 16:56:08.148,Fulton Market,CHI01880,NaN,NaN,41.886871,-87.648089,NaN,NaN,member
5473075,E87E123751FA42E1,classic_bike,2026-04-30 17:27:25.585,2026-05-01 18:27:01.264,Canal St & Madison St,CHI00498,NaN,NaN,41.882409,-87.639767,NaN,NaN,casual
5481340,D582320F33836B82,electric_bike,2026-04-30 23:55:35.449,2026-05-01 00:04:50.335,NaN,NaN,NaN,NaN,41.940000,-87.680000,41.940000,-87.680000,member
5497704,76D09A47149E1197,electric_bike,2026-04-30 23:58:01.713,2026-05-01 00:01:16.350,Southport Ave & Roscoe St,CHI00234,NaN,NaN,41.943739,-87.664020,41.930000,-87.660000,member
5501372,4B93DFFDA6B08DE5,electric_bike,2026-04-30 23:11:10.108,2026-05-01 00:04:42.964,NaN,NaN,NaN,NaN,41.900000,-87.620000,41.810000,-87.640000,member
5503042,69451215A387162E,electric_bike,2026-04-30 23:57:55.143,2026-05-01 00:03:07.980,Green St & Randolph St,CHI01988,NaN,NaN,41.883602,-87.648627,41.880000,-87.640000,member
5509887,AE8BAD810DCE9D27,classic_bike,2026-04-30 12:50:47.359,2026-05-01 13:50:40.292,Campbell Ave & Montrose Ave,CHI00214,NaN,NaN,41.961524,-87.691177,NaN,NaN,member
5511732,BD39C82BE83AED87,electric_bike,2026-04-30 23:30:07.772,2026-05-01 00:52:55.807,NaN,NaN,NaN,NaN,41.970000,-87.640000,41.940000,-87.640000,member
5511750,C71ACD907F4C4B61,electric_bike,2026-04-30 23:58:56.151,2026-05-01 00:01:21.877,NaN,NaN,NaN,NaN,42.050000,-87.690000,42.050000,-87.690000,member
5512508,47B00C2CFA51BED8,electric_bike,2026-04-30 23:50:55.156,2026-05-01 00:00:40.360,NaN,NaN,NaN,NaN,41.940000,-87.650000,41.970000,-87.650000,member
5522652,82EDB771CE5282E8,classic_bike,2026-04-30 00:34:54.913,2026-05-01 01:09:44.373,Wentworth Ave & 35th St,CHI02033,Ellis Ave & 55th St,CHI00583,41.830777,-87.632504,41.794301,-87.601450,casual
5586984,96EC33CC33D9FB6D,electric_bike,2026-04-30 23:55:14.467,2026-05-01 00:05:01.432,Damen Ave & Melrose Ave,CHI00516,Damen Ave & Melrose Ave,CHI00516,41.940600,-87.678500,41.940600,-87.678500,casual
5609505,4EBCC6DF233878B6,classic_bike,2026-04-30 23:57:58.221,2026-05-01 00:02:42.981,Green St & Randolph St,CHI01988,Clinton St & Madison St,CHI00233,41.883602,-87.648627,41.881660,-87.641150,member
5609512,EAB7C279D822C763,classic_bike,2026-04-30 23:58:36.620,2026-05-01 00:02:45.401,Green St & Randolph St,CHI01988,Clinton St & Madison St,CHI00233,41.883602,-87.648627,41.881660,-87.641150,member
5609514,5232F2CB3D297D55,classic_bike,2026-04-30 23:57:23.904,2026-05-01 00:02:12.022,Green St & Randolph St,CHI01988,Clinton St & Madison St,CHI00233,41.883602,-87.648627,41.881660,-87.641150,member
5613023,15521787039F37E5,classic_bike,2026-04-30 23:54:44.934,2026-05-01 00:05:45.575,Michigan Ave & 11th St,CHI02025,DuSable Lake Shore Dr & Monroe St,CHI00374,41.869590,-87.623961,41.880958,-87.616743,member
5619507,3D8B4B1B10438A9F,electric_bike,2026-04-30 23:48:09.859,2026-05-01 00:03:08.550,LaSalle Dr & Huron St,CHI00640,Pine Grove Ave & Waveland Ave,CHI00354,41.894877,-87.632326,41.949473,-87.646453,member
5648651,E923A7ACDD4A9293,classic_bike,2026-04-30 23:58:06.960,2026-05-01 00:00:34.820,Clinton St & Lake St,CHI01746,Wacker Dr & Washington St,CHI01787,41.885637,-87.641823,41.883143,-87.637242,casual
5681040,41E2750A57535CF7,electric_bike,2026-04-30 23:58:04.347,2026-05-01 00:12:39.854,Albany Ave & Montrose Ave,CHI01768,Clarendon Ave & Junior Ter,CHI00395,41.961041,-87.705866,41.961004,-87.649603,casual
5731714,03C5375398BE0649,electric_bike,2026-04-30 23:46:36.039,2026-05-01 00:04:48.512,NaN,NaN,Clark St & Arlington Pl,CHI02109,41.900000,-87.630000,41.926940,-87.641480,member
5774625,C9050956F58561AD,classic_bike,2026-04-30 23:56:44.348,2026-05-01 00:00:36.790,Halsted St & Dickens Ave,CHI00291,Halsted St & Belden St,CHI02105,41.919936,-87.648830,41.923650,-87.648940,casual
5775045,B046AA82A096C6FA,classic_bike,2026-04-30 23:57:36.481,2026-05-01 00:00:40.736,Halsted St & Dickens Ave,CHI00291,Halsted St & Belden St,CHI02105,41.919936,-87.648830,41.923650,-87.648940,member
5788125,437C637BFCE893DE,classic_bike,2026-04-30 14:17:59.569,2026-05-01 15:17:38.941,Dusable Harbor,CHI00531,NaN,NaN,41.886976,-87.612813,NaN,NaN,casual
5809873,67C08EEA3F45893E,classic_bike,2026-04-30 13:01:01.483,2026-05-01 14:00:39.251,Millennium Park,CHI01742,NaN,NaN,41.881032,-87.624084,NaN,NaN,casual
5811463,1DB04E901469FB2F,electric_bike,2026-04-30 23:54:09.726,2026-05-01 00:11:09.709,Ravenswood Ave & Irving Park Rd,CHI00309,NaN,NaN,41.954690,-87.673930,41.970000,-87.670000,casual

In [6]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [7]:
df["started_at"]= pd.to_datetime(df["started_at"])
df["started_at"].dtypes

dtype('<M8[ns]')

In [8]:
df["ended_at"] = pd.to_datetime(df["ended_at"])

In [20]:
df.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [9]:
df["ride_length"]=df["ended_at"]-df["started_at"]
df["ride_length"]

0         0 days 00:13:48.342000
1         0 days 00:09:45.313000
2         0 days 00:09:31.100000
3         0 days 00:12:05.477000
4         0 days 00:10:10.480000
                   ...
5848698   0 days 00:00:43.702000
5848699   0 days 00:00:02.845000
5848700   0 days 00:12:06.224000
5848701   0 days 00:07:58.496000
5848702   0 days 00:07:49.873000
Name: ride_length, Length: 5848703, dtype: timedelta64[ns]

In [10]:
df[df["ended_at"] < df["started_at"]]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
3618432,5D010AFEA6850513,electric_bike,2025-11-02 01:52:37.475,2025-11-02 01:13:24.728,Pine Grove Ave & Wellington Ave,CHI02158,Wilton Ave & Addison St,CHI02055,41.936510,-87.641190,41.947459,-87.653216,member,-1 days +23:20:47.253000
3619980,D1E5316AD88ECD45,classic_bike,2025-11-02 01:50:39.702,2025-11-02 01:14:04.164,Clark St & Ida B Wells Dr,CHI00216,Paulina St & Division St,CHI00244,41.875933,-87.630585,41.903553,-87.670429,casual,-1 days +23:23:24.462000
3621974,3AF2F8908C9386F8,classic_bike,2025-11-02 01:57:57.512,2025-11-02 01:33:52.225,State St & Chicago Ave,CHI01772,Ravenswood Ave & Berteau Ave,CHI00471,41.896617,-87.628579,41.957921,-87.673567,member,-1 days +23:35:54.713000
3636870,19386939ECD81B33,electric_bike,2025-11-02 01:55:34.399,2025-11-02 01:21:31.873,Broadway & Sheridan Rd,CHI00476,NaN,NaN,41.952833,-87.649993,41.960000,-87.740000,member,-1 days +23:25:57.474000
3645238,083534D28DA37F72,classic_bike,2025-11-02 01:17:57.001,2025-11-02 01:05:27.752,Clark St & Grace St,CHI00301,Grace St & Central Ave,CHI01799,41.950780,-87.659172,41.949533,-87.767265,member,-1 days +23:47:30.751000
3689823,4A659F1BB40EDBF7,electric_bike,2025-11-02 01:55:38.177,2025-11-02 01:04:35.315,Keystone Ave & Montrose Ave,CHI00643,Lynch Ave & Elston Ave,CHI02000,41.961108,-87.728970,41.980960,-87.761490,casual,-1 days +23:08:57.138000
3715376,DA5386E5759667EC,electric_bike,2025-11-02 01:51:31.704,2025-11-02 01:05:47.339,Racine Ave & Belmont Ave,CHI00411,Dearborn St & Division St,CHI02125,41.939743,-87.658865,41.904300,-87.629910,member,-1 days +23:14:15.635000
3720834,985A3462DAACFFCF,classic_bike,2025-11-02 01:59:07.835,2025-11-02 01:05:19.214,Seminary Ave & Belden Ave,CHI02106,Sedgwick St & Webster Ave,CHI00487,41.923390,-87.655990,41.922167,-87.638888,member,-1 days +23:06:11.379000
3740757,434E3D11ABA96891,electric_bike,2025-11-02 01:59:40.156,2025-11-02 01:08:51.303,Public Rack - Olmstead Ave & Oliphant Ave,CHI01613,Milwaukee Ave & Highland Ave,CHI02015,42.002311,-87.817095,41.996360,-87.786740,casual,-1 days +23:09:11.147000
3750575,9288498F5630E3AD,electric_bike,2025-11-02 01:49:48.360,2025-11-02 01:02:40.976,Damen Ave & Thomas St (Augusta Blvd),CHI00296,NaN,NaN,41.901315,-87.677409,41.870000,-87.680000,casual,-1 days +23:12:52.616000
3750592,12E0A9A586A45DE3,electric_bike,2025-11-02 01:49:41.788,2025-11-02 01:02:30.041,Damen Ave & Thomas St (Augusta Blvd),CHI00296,NaN,NaN,41.901315,-87.677409,41.870000,-87.680000,member,-1 days +23:12:48.253000
3751960,222A5E8650C55311,electric_bike,2025-11-02 01:55:51.266,2025-11-02 01:01:50.026,W Armitage Ave & N Sheffield Ave,CHI00836,NaN,NaN,41.917805,-87.653449,41.910000,-87.640000,member,-1 days +23:05:58.760000
3760728,83995E751A0DB5D5,electric_bike,2025-11-02 01:50:50.530,2025-11-02 01:01:15.026,Paulina St & Division St,CHI00244,Kedzie Ave & Milwaukee Ave,CHI00378,41.903553,-87.670429,41.929714,-87.707988,member,-1 days +23:10:24.496000
3793782,120BC0544C3B92E4,classic_bike,2025-11-02 01:41:32.055,2025-11-02 01:08:10.359,Clark St & Chicago Ave,CHI00351,Clark St & Wrightwood Ave,CHI00287,41.896750,-87.630890,41.929546,-87.643118,casual,-1 days +23:26:38.304000
3793886,4446901DBDE0531B,classic_bike,2025-11-02 01:45:25.021,2025-11-02 01:08:08.134,Clark St & Chicago Ave,CHI00351,Clark St & Wrightwood Ave,CHI00287,41.896750,-87.630890,41.929546,-87.643118,casual,-1 days +23:22:43.113000
3804972,ED8C9D500F271C3D,classic_bike,2025-11-02 01:57:24.553,2025-11-02 01:02:44.165,Racine Ave & Randolph St,CHI00320,Ogden Ave & Chicago Ave,CHI00275,41.884081,-87.656921,41.896362,-87.654061,member,-1 days +23:05:19.612000
3806330,4976DE4C5F1AA516,electric_bike,2025-11-02 01:56:44.152,2025-11-02 01:06:51.164,NaN,NaN,Sedgwick St & Huron St,CHI00241,41.920000,-87.640000,41.894666,-87.638437,member,-1 days +23:10:07.012000
3806707,3301C8D1FF15E4CE,electric_bike,2025-11-02 01:58:08.316,2025-11-02 01:16:43.649,Manor Ave & Leland Ave,CHI00633,Damen Ave & Division St,CHI00318,41.965875,-87.700825,41.903266,-87.678435,member,-1 days +23:18:35.333000
3828522,A66DEC9146C488BF,electric_bike,2025-11-02 01:50:17.559,2025-11-02 01:07:46.445,NaN,NaN,Wilton Ave & Addison St,CHI02055,42.000000,-87.670000,41.947459,-87.653216,member,-1 days +23:17:28.886000
3830791,595AED6AB9A66E8F,classic_bike,2025-11-02 01:51:37.195,2025-11-02 01:18:08.912,Michigan Ave & Oak St,CHI00252,Sedgwick St & Webster Ave,CHI00487,41.900960,-87.623777,41.922167,-87.638888,member,-1 days +23:26:31.717000
3834331,5740B9AA6176D32C,classic_bike,2025-11-02 01:59:56.801,2025-11-02 01:05:09.113,Western Blvd & 48th Pl,CHI00735,Campbell Ave & 51st St,CHI01918,41.805661,-87.683392,41.800940,-87.686760,member,-1 days +23:05:12.312000
3853895,A61B896123C0D647,classic_bike,2025-11-02 01:28:03.715,2025-11-02 01:05:17.029,Sacramento Ave & Lyndale St,CHI02126,Rush St & Cedar St,CHI00537,41.922350,-87.702410,41.902309,-87.627691,casual,-1 days +23:37:13.314000
3857147,093B3FC8E465DA4A,electric_bike,2025-11-02 01:52:58.523,2025-11-02 01:04:31.464,NaN,NaN,Wabash Ave & Roosevelt Rd,CHI00524,41.860000,-87.620000,41.867227,-87.625961,member,-1 days +23:11:32.941000
3858622,C89AFBD919D615FD,classic_bike,2025-11-02 01:51:49.264,2025-11-02 01:18:50.977,Sedgwick St & Huron St,CHI00241,Southport Ave & Irving Park Rd,CHI00481,41.894666,-87.638437,41.954177,-87.664358,member,-1 days +23:27:01.713000
3868135,8BF21DA40F846779,electric_bike,2025-11-02 01:57:17.456,2025-11-02 01:26:23.644,Campbell Ave & North Ave,CHI00341,Campbell Ave & North Ave,CHI00341,41.910535,-87.689556,41.910535,-87.689556,member,-1 days +23:29:06.188000
3869547,01C21B340CC1EEDA,classic_bike,2025-11-02 01:50:43.657,2025-11-02 01:03:13.912,California Ave & Milwaukee Ave,CHI00307,Paulina Ave & North Ave,CHI00258,41.922695,-87.697153,41.909855,-87.669930,casual,-1 days +23:12:30.255000
3870689,F87FA50B8D40FA97,electric_bike,2025-11-02 01:54:25.185,2025-11-02 01:10:50.859,NaN,NaN,Michigan Ave & Madison St,CHI01915,41.880000,-87.640000,41.882134,-87.625125,casual,-1 days +23:16:25.674000
3903270,5F7692C857079901,electric_bike,2025-11-02 01:54:17.357,2025-11-02 01:13:50.718,Clark St & Leland Ave,CHI00461,NaN,NaN,41.967088,-87.667291,41.960000,-87.660000,member,-1 days +23:19:33.361000
3936262,E37AEB3E9CE2343E,electric_bike,2025-11-02 01:56:26.465,2025-11-02 01:03:08.183,Broadway & Roscoe Ave,CHI02153,NaN,NaN,41.943600,-87.645320,41.960000,-87.650000,member,-1 days +23:06:41.718000

In [12]:
df_cleaned=df[df["ended_at"]>=df["started_at"]].copy()
df_cleaned

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,0 days 00:13:48.342000
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:45.313000
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:31.100000
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,0 days 00:12:05.477000
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,0 days 00:10:10.480000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5848698,F319CE4AE531709B,electric_bike,2026-05-02 15:34:11.090,2026-05-02 15:34:54.792,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,casual,0 days 00:00:43.702000
5848699,C74AD329966F1E3D,electric_bike,2026-05-06 22:11:10.776,2026-05-06 22:11:13.621,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,member,0 days 00:00:02.845000
5848700,944F31B24AEACDCB,electric_bike,2026-05-31 16:49:33.315,2026-05-31 17:01:39.539,Ada St & Washington Blvd,CHI00278,Damen Ave & Thomas St (Augusta Blvd),CHI00296,41.882830,-87.661206,41.901315,-87.677409,member,0 days 00:12:06.224000
5848701,DCA6A24FC420D5AF,electric_bike,2026-05-20 18:35:36.360,2026-05-20 18:43:34.856,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:58.496000
5848702,4C020D893130AC87,electric_bike,2026-05-26 08:15:05.915,2026-05-26 08:22:55.788,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:49.873000

In [14]:
df_cleaned.drop_duplicates()
df_cleaned

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,0 days 00:13:48.342000
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:45.313000
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:31.100000
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,0 days 00:12:05.477000
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,0 days 00:10:10.480000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5848698,F319CE4AE531709B,electric_bike,2026-05-02 15:34:11.090,2026-05-02 15:34:54.792,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,casual,0 days 00:00:43.702000
5848699,C74AD329966F1E3D,electric_bike,2026-05-06 22:11:10.776,2026-05-06 22:11:13.621,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,member,0 days 00:00:02.845000
5848700,944F31B24AEACDCB,electric_bike,2026-05-31 16:49:33.315,2026-05-31 17:01:39.539,Ada St & Washington Blvd,CHI00278,Damen Ave & Thomas St (Augusta Blvd),CHI00296,41.882830,-87.661206,41.901315,-87.677409,member,0 days 00:12:06.224000
5848701,DCA6A24FC420D5AF,electric_bike,2026-05-20 18:35:36.360,2026-05-20 18:43:34.856,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:58.496000
5848702,4C020D893130AC87,electric_bike,2026-05-26 08:15:05.915,2026-05-26 08:22:55.788,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:49.873000

In [16]:
df_cleaned["day_of_week"] = ((df_cleaned["started_at"].dt.dayofweek + 1) % 7)+1
df_cleaned

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,0 days 00:13:48.342000,5
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:45.313000,7
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:31.100000,2
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,0 days 00:12:05.477000,1
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,0 days 00:10:10.480000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5848698,F319CE4AE531709B,electric_bike,2026-05-02 15:34:11.090,2026-05-02 15:34:54.792,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,casual,0 days 00:00:43.702000,7
5848699,C74AD329966F1E3D,electric_bike,2026-05-06 22:11:10.776,2026-05-06 22:11:13.621,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,member,0 days 00:00:02.845000,4
5848700,944F31B24AEACDCB,electric_bike,2026-05-31 16:49:33.315,2026-05-31 17:01:39.539,Ada St & Washington Blvd,CHI00278,Damen Ave & Thomas St (Augusta Blvd),CHI00296,41.882830,-87.661206,41.901315,-87.677409,member,0 days 00:12:06.224000,1
5848701,DCA6A24FC420D5AF,electric_bike,2026-05-20 18:35:36.360,2026-05-20 18:43:34.856,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:58.496000,4
5848702,4C020D893130AC87,electric_bike,2026-05-26 08:15:05.915,2026-05-26 08:22:55.788,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:49.873000,3

In [17]:
station_df = df_cleaned[df_cleaned["start_station_name"].notna()]
station_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,0 days 00:13:48.342000,5
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:45.313000,7
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,0 days 00:09:31.100000,2
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,0 days 00:12:05.477000,1
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,0 days 00:10:10.480000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5848698,F319CE4AE531709B,electric_bike,2026-05-02 15:34:11.090,2026-05-02 15:34:54.792,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,casual,0 days 00:00:43.702000,7
5848699,C74AD329966F1E3D,electric_bike,2026-05-06 22:11:10.776,2026-05-06 22:11:13.621,Sheffield Ave & Waveland Ave,CHI00310,Sheffield Ave & Waveland Ave,CHI00310,41.949399,-87.654529,41.949399,-87.654529,member,0 days 00:00:02.845000,4
5848700,944F31B24AEACDCB,electric_bike,2026-05-31 16:49:33.315,2026-05-31 17:01:39.539,Ada St & Washington Blvd,CHI00278,Damen Ave & Thomas St (Augusta Blvd),CHI00296,41.882830,-87.661206,41.901315,-87.677409,member,0 days 00:12:06.224000,1
5848701,DCA6A24FC420D5AF,electric_bike,2026-05-20 18:35:36.360,2026-05-20 18:43:34.856,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:58.496000,4
5848702,4C020D893130AC87,electric_bike,2026-05-26 08:15:05.915,2026-05-26 08:22:55.788,Sheffield Ave & Wrightwood Ave,CHI00465,Sheffield Ave & Waveland Ave,CHI00310,41.928712,-87.653833,41.949399,-87.654529,member,0 days 00:07:49.873000,3

In [18]:
df_cleaned["ride_length"].describe()

count                      5848674
mean     0 days 00:15:59.218051002
std      0 days 00:55:06.176821738
min         0 days 00:00:00.046000
25%         0 days 00:05:22.341000
50%         0 days 00:09:24.131000
75%         0 days 00:16:32.843000
max         1 days 02:14:54.011000
Name: ride_length, dtype: object

In [19]:
df_cleaned["ride_length"].mean()

Timedelta('0 days 00:15:59.218051002')

In [20]:
df_cleaned["ride_length"].max()

Timedelta('1 days 02:14:54.011000')

In [21]:
df_cleaned["day_of_week"].mode()

0    7
Name: day_of_week, dtype: int64

In [22]:
df_cleaned["day_of_week"].value_counts().sort_index()

day_of_week
1    774672
2    772517
3    827388
4    830963
5    868632
6    872104
7    902398
Name: count, dtype: int64

In [23]:
df_cleaned.groupby("member_casual")["ride_length"].mean()

member_casual
casual   0 days 00:22:15.668398791
member   0 days 00:12:28.291174211
Name: ride_length, dtype: timedelta64[ns]

In [43]:
df_cleaned.groupby(["member_casual", "day_of_week"])["ride_length"].mean()

member_casual  day_of_week
casual         1             0 days 00:25:39.027415892
               2             0 days 00:22:16.919015493
               3             0 days 00:19:20.895419216
               4             0 days 00:18:38.136763007
               5             0 days 00:19:34.715944472
               6             0 days 00:21:53.714281083
               7             0 days 00:24:55.110270397
member         1             0 days 00:13:40.309219047
               2             0 days 00:12:12.422503816
               3             0 days 00:12:00.079740273
               4             0 days 00:11:58.042794536
               5             0 days 00:11:59.358723995
               6             0 days 00:12:21.570849064
               7             0 days 00:13:41.363687387
Name: ride_length, dtype: timedelta64[ns]

In [24]:
df_cleaned.groupby(["member_casual", "day_of_week"])["ride_id"].count()

member_casual  day_of_week
casual         1              360297
               2              245260
               3              234845
               4              236518
               5              267112
               6              323398
               7              432826
member         1              414375
               2              527257
               3              592543
               4              594445
               5              601520
               6              548706
               7              469572
Name: ride_id, dtype: int64

In [37]:
df_cleaned["hour"] = df_cleaned["started_at"].dt.hour

df_cleaned.groupby("hour")["ride_id"].count()

hour
0      75508
1      47717
2      30427
3      18125
4      17008
5      48400
6     133534
7     261674
8     347215
9     247231
10    237225
11    286898
12    332098
13    333149
14    344302
15    411997
16    541074
17    606002
18    485421
19    346823
20    245801
21    197680
22    152605
23    100760
Name: ride_id, dtype: int64

In [26]:
df_sample.dtypes

ride_id                        object
rideable_type                  object
started_at             datetime64[ns]
ended_at               datetime64[ns]
start_station_name             object
start_station_id               object
end_station_name               object
end_station_id                 object
start_lat                     float64
start_lng                     float64
end_lat                       float64
end_lng                       float64
member_casual                  object
ride_length           timedelta64[ns]
day_of_week                     int64
dtype: object

In [41]:
df_cleaned["ride_length_minutes"] = (
    df_cleaned["ride_length"].dt.total_seconds() / 60
)

In [27]:
df_sample = df_cleaned.sample(n=500000, random_state=42)
df_sample

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
2995116,5E81FE1D7DA81A05,classic_bike,2025-10-19 18:31:42.998,2025-10-19 18:37:04.344,Kimbark Ave & 53rd St,CHI00490,University Ave & 57th St,CHI00551,41.799455,-87.594778,41.791478,-87.599861,member,0 days 00:05:21.346000,1
4473442,A055DAE6A1C7E33E,electric_bike,2026-03-30 17:05:40.164,2026-03-30 17:07:33.702,NaN,NaN,NaN,NaN,41.890000,-87.650000,41.890000,-87.640000,casual,0 days 00:01:53.538000,2
2792440,06EDB79AA6122187,electric_bike,2025-09-20 19:13:08.469,2025-09-20 19:18:21.177,NaN,NaN,NaN,NaN,41.930000,-87.730000,41.940000,-87.720000,member,0 days 00:05:12.708000,7
1010341,F04D6750F9205313,electric_bike,2025-07-28 17:29:14.282,2025-07-28 17:42:58.656,Shedd Aquarium,CHI00533,Millennium Park,CHI01742,41.867226,-87.615355,41.881032,-87.624084,casual,0 days 00:13:44.374000,2
4806131,D12234379A4CD905,electric_bike,2026-04-06 23:40:46.344,2026-04-06 23:46:31.343,Clark St & Wellington Ave,CHI00377,Broadway & Waveland Ave,CHI00496,41.936497,-87.647539,41.949074,-87.648636,member,0 days 00:05:44.999000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2585563,D0C179A5E7BD1D01,electric_bike,2025-09-07 11:08:52.006,2025-09-07 11:12:57.019,NaN,NaN,Ravenswood Ave & Berteau Ave,CHI00471,41.950000,-87.670000,41.957921,-87.673567,member,0 days 00:04:05.013000,1
1217526,093B9CE4FAA8282D,classic_bike,2025-07-16 21:54:26.502,2025-07-16 22:17:46.620,McClurg Ct & Ohio St,CHI00330,Lincoln Park Conservatory,CHI00626,41.892592,-87.617289,41.923931,-87.635825,casual,0 days 00:23:20.118000,4
2568716,C53B6A4994987C33,electric_bike,2025-09-13 13:00:27.117,2025-09-13 13:21:35.334,NaN,NaN,Dearborn Pkwy & Delaware Pl,CHI00306,41.960000,-87.650000,41.898969,-87.629912,member,0 days 00:21:08.217000,7
520463,5817F6F52BE272D3,electric_bike,2025-06-01 11:23:45.526,2025-06-01 11:24:13.981,DuSable Lake Shore Dr & North Blvd,CHI00525,DuSable Lake Shore Dr & North Blvd,CHI00525,41.911722,-87.626804,41.911722,-87.626804,member,0 days 00:00:28.455000,1
885735,42619B766D0A1C40,classic_bike,2025-07-02 17:05:02.828,2025-07-02 17:09:53.557,Green St & Randolph St*,CHI01988,Aberdeen St & Jackson Blvd,CHI00406,41.883602,-87.648627,41.877726,-87.654787,member,0 days 00:04:50.729000,4

In [48]:
df_sample.to_csv("df_sample.csv", index=False)